# Generated by Django 3.0 on 2021-11-28 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('proba', models.FloatField(default=0.0)),
                ('registered_date', models.DateField(default=datetime.date(2021, 11, 28))),
            ],
        ),
    ]
