# Generated by Django 3.0 on 2021-12-04 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AlterField(
            model_name='image',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
