# Generated by Django 3.0 on 2021-12-12 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0002_auto_20211204_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='proba',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
